# Generated by Django 3.2.6 on 2021-08-31 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='uuid',
            field=models.CharField(default='asgeasg', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='type_of',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
