# Generated by Django 3.2.6 on 2021-08-31 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0002_auto_20210831_0759'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='max_tables',
            field=models.PositiveIntegerField(default=3),
        ),
    ]
