# Generated by Django 3.2.6 on 2021-08-31 18:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0004_restaurant_pricipal_menu'),
    ]

    operations = [
        migrations.RenameField(
            model_name='restaurant',
            old_name='pricipal_menu',
            new_name='main_menu',
        ),
    ]
