# Generated by Django 3.2.6 on 2021-09-02 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0005_rename_pricipal_menu_restaurant_main_menu'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='slug',
            field=models.SlugField(default='ostreria-italiana', max_length=100, unique=True),
            preserve_default=False,
        ),
    ]
