# Generated by Django 3.2.6 on 2021-09-07 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0007_alter_restaurant_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='welcome_message',
            field=models.CharField(blank=True, max_length=105, null=True),
        ),
    ]
