# Generated by Django 3.2.6 on 2021-09-13 06:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0008_restaurant_welcome_message'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='restaurant',
            name='max_tables',
        ),
    ]
