# Generated by Django 3.2.6 on 2021-09-13 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0009_remove_restaurant_max_tables'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='max_tables',
            field=models.PositiveIntegerField(default=3),
        ),
    ]
