# Generated by Django 3.2.6 on 2021-09-14 07:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0013_auto_20210914_0200'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='restaurant',
            name='max_tables',
        ),
    ]
