# Generated by Django 3.2.6 on 2021-09-19 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0014_remove_restaurant_max_tables'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='kitchen',
            field=models.CharField(default='asd', max_length=255),
            preserve_default=False,
        ),
    ]
