# Generated by Django 3.2.6 on 2021-09-07 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dishes', '0003_dish_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='dish',
            name='featured',
            field=models.BooleanField(default=False),
        ),
    ]
