# Generated by Django 3.2.6 on 2021-09-09 00:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dishes', '0005_discount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discount',
            name='dish',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='discount', to='dishes.dish'),
        ),
        migrations.CreateModel(
            name='Specific',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('type_of', models.CharField(max_length=20)),
                ('limit', models.PositiveIntegerField(blank=True, null=True)),
                ('dish', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='specifics', to='dishes.dish')),
            ],
        ),
        migrations.CreateModel(
            name='OptionField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('specific', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='dishes.specific')),
            ],
        ),
    ]
