# Generated by Django 3.2.6 on 2021-09-10 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dishes', '0006_auto_20210909_0036'),
    ]

    operations = [
        migrations.AddField(
            model_name='dish',
            name='calories',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dish',
            name='duration',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
