# Generated by Django 3.2.6 on 2021-09-01 05:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tables', '0001_initial'),
        ('restaurants', '0005_rename_pricipal_menu_restaurant_main_menu'),
    ]

    operations = [
        migrations.CreateModel(
            name='Check',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.CharField(max_length=255)),
                ('payment_method', models.CharField(max_length=20)),
                ('was_split', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('total_amount', models.PositiveIntegerField()),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checks', to='restaurants.restaurant')),
                ('table', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='checks', to='tables.table')),
            ],
        ),
        migrations.CreateModel(
            name='SoloCheck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer', models.CharField(blank=True, max_length=30, null=True)),
                ('payment_method', models.CharField(max_length=20)),
                ('amount', models.PositiveIntegerField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('_check', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='solo_checks', to='checks.check')),
            ],
        ),
        migrations.CreateModel(
            name='JackpotCheck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_method', models.CharField(max_length=20)),
                ('amount', models.PositiveIntegerField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('_check', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='jackpot_checks', to='checks.check')),
            ],
        ),
    ]
