# Generated by Django 3.2.6 on 2021-09-01 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checks', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='solocheck',
            name='_check',
        ),
        migrations.AddField(
            model_name='check',
            name='closed',
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name='JackpotCheck',
        ),
        migrations.DeleteModel(
            name='SoloCheck',
        ),
    ]
