# Generated by Django 3.2.6 on 2021-09-19 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kitchens', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kitchen',
            name='uuid',
            field=models.CharField(max_length=255),
        ),
    ]
