# Generated by Django 3.2.6 on 2021-09-19 06:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0015_restaurant_kitchen'),
        ('kitchens', '0002_alter_kitchen_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kitchen',
            name='restaurant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kitchens', to='restaurants.restaurant'),
        ),
    ]
