# Generated by Django 3.2.6 on 2021-09-14 07:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0002_alter_account_image'),
        ('restaurants', '0013_auto_20210914_0200'),
    ]

    operations = [
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_of', models.CharField(default='free', max_length=20)),
                ('pricing', models.PositiveIntegerField(default=0)),
                ('paid_until', models.DateField()),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plans', to='users.account')),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plans', to='restaurants.restaurant')),
            ],
        ),
    ]
