# Generated by Django 3.2.6 on 2021-09-14 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plan',
            name='paid_until',
            field=models.DateField(blank=True, null=True),
        ),
    ]
