# Generated by Django 3.2.6 on 2021-09-14 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0002_alter_plan_paid_until'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='max_orders',
            field=models.PositiveIntegerField(default=100),
        ),
        migrations.AddField(
            model_name='plan',
            name='max_tables',
            field=models.PositiveIntegerField(default=3),
        ),
    ]
