# Generated by Django 3.2.6 on 2021-09-19 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0003_auto_20210914_0739'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plan',
            name='max_orders',
            field=models.PositiveIntegerField(default=50),
        ),
    ]
