# Generated by Django 3.2.6 on 2021-09-06 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menus', '0002_auto_20210831_0848'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='main',
            field=models.BooleanField(default=False),
        ),
    ]
