# Generated by Django 3.2.6 on 2021-09-07 16:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menus', '0003_menu_main'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menu',
            name='main',
        ),
    ]
